#!/bin/bash
curl -L https://github.com/balena-io/qemu/releases/download/v4.0.0%2Bbalena2/qemu-4.0.0.balena2-arm.tar.gz | tar zxvf - -C . && mv qemu-4.0.0+balena2-arm/qemu-arm-static .
curl -L https://github.com/balena-io/qemu/releases/download/v4.0.0%2Bbalena2/qemu-4.0.0.balena2-aarch64.tar.gz | tar zxvf - -C . && mv qemu-4.0.0+balena2-aarch64\qemu-aarch64-static .